language: cpp
services:
  - docker
before_install:
  - docker build -f docker/Dockerfile.ad.provdb -t chimbuko/ad:ubuntu18.04-provdb .
script: docker run -it chimbuko/ad:ubuntu18.04-provdb
addons:
  apt:
    packages:
      - docker-ce
