#FROM chimbuko/sosflow:latest
FROM chimbuko/perfanal:latest

# ----------------------------------------------------------------------------
# Install some required packages
# ----------------------------------------------------------------------------
RUN apt-get install -y libopenblas-base libopenblas-dev

# ----------------------------------------------------------------------------
# set environment variables
# ----------------------------------------------------------------------------
#ENV export PATH=${PATH}:/opt/sos_flow/bin
ENV export PATH=${PATH}:/opt/papi/bin
ENV PATH=${PATH}:/opt/pdt/x86_64/bin
ENV PATH=${PATH}:/opt/tau2/x86_64/bin

#ENV LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/opt/sos_flow/lib
ENV LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/opt/papi/lib
ENV LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/opt/pdt/x86_64/lib
ENV LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/opt/tau2/x86_64/lib
#ENV LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/opt/jemalloc/lib

# this depends on how tau2 is compiled
# NOTE: TAU_MAKEFILE depends on how tau2 is compiled. Need to be changed 
# accordingly. Are there better way like the second example that doesn't work? 
ENV TAU_MAKEFILE=/opt/tau2/x86_64/lib/Makefile.tau-papi-mpi-pthread-pdt-adios2

#ENV TAU_MAKEFILE="`find /opt/tau2/x86_64/lib -name Makefile.tau*`"

# -----------------------------------------------------------------------------
# NWCHEM installation
# - pretauadio2: adios part was taken away in this version
# -----------------------------------------------------------------------------
RUN mkdir -p /Codar
WORKDIR /Codar
RUN git clone https://github.com/hjjvandam/nwchem-1.git
WORKDIR /Codar/nwchem-1
RUN git checkout pretauadio2

# to enable tau compiler for nwchem
ENV USE_TAU="source"
ENV ARMCI_NETWORK=MPI-TS
ENV BLASOPT="-lopenblas `adios2-config -c -f`"
ENV NWCHEM_MODULES=md
RUN ./contrib/distro-tools/build_nwchem 2>&1 | tee build_nwchem.log

# create .nwchemrc file using /Codar/nwchem-1/QA/domknwchemrc
# The script must run in the QA folder!!!!!!!!!!!!!!!!!!
WORKDIR /Codar/nwchem-1/QA
RUN ./domknwchemrc

WORKDIR /Codar/nwchem-1

# Check point if it doesn't work
# check environment variable
# - PATH, LD_LIBRARY_PATH, 
# - USE_TAU
# - ~/.nwchemrc (must run in the QA folder! ./QA/domknwchemrc)
