FROM chimbuko/adios2.cuda10.1 AS ad-build

WORKDIR /Downloads

RUN git clone -b ckelly_develop https://github.com/CODARcode/PerformanceAnalysis.git
RUN cd PerformanceAnalysis/ && ./autogen.sh

WORKDIR /build

RUN CC=mpicc CXX=mpicxx ../Downloads/PerformanceAnalysis/configure --with-adios2=/opt/adios2 --with-network=ZMQ --with-perf-metric --prefix=/opt/chimbuko/ad

RUN make -j 4 install && cd /opt/chimbuko/ad/test

ENV LD_LIBRARY_PATH=/usr/local/cuda/compat:/usr/local/cuda/lib64:${LD_LIBRARY_PATH}

WORKDIR /opt/chimbuko/ad/test
RUN cat run_net.sh | sed 's/-n 10/--oversubscribe -n 10/' > tmp && mv tmp run_net.sh && chmod u+x run_net.sh && ./run_all.sh

#	&& ./run_all.sh


FROM chimbuko/adios2.cuda10.1

RUN mkdir -p /opt/chimbuko/ad
COPY --from=ad-build /opt/chimbuko/ad /opt/chimbuko/ad

WORKDIR /opt/chimbuko/ad/test
ENTRYPOINT [ "./run_all.sh" ]
