FROM chimbuko/base AS viz-build

RUN mkdir -p /Downloads && cd /Downloads && \
    git clone https://github.com/bsmind/ChimbukoVisualizationII.git && \
    cd ChimbukoVisualizationII && \
    curl -O http://download.redis.io/redis-stable.tar.gz && \
    tar xvzf redis-stable.tar.gz &&  rm redis-stable.tar.gz && \
    cd redis-stable && make

FROM chimbuko/base

RUN mkdir -p /opt/chimbuko/viz
COPY --from=viz-build /Downloads/ChimbukoVisualizationII /opt/chimbuko/viz

WORKDIR /
