# chimbuko/adios2:brusselator suports zfp that is required to run Brusselator 
# Note that chimbuko/adios2:latest doesn't support zfp.
FROM chimbuko/adios2.cuda10.1:latest AS tau-build
ARG JOBS=4

# --------------------------------------------------------
# TAU
# --------------------------------------------------------

# PDT

WORKDIR /Downloads
RUN wget http://tau.uoregon.edu/pdt_lite.tar.gz \
 && tar -xzf pdt_lite.tar.gz
WORKDIR /Downloads/pdtoolkit-3.25.1
RUN ./configure -GNU -prefix=/opt/pdt \
 && make -j$JOBS \
 && make install

# PAPI

WORKDIR /Downloads
RUN wget http://icl.utk.edu/projects/papi/downloads/papi-5.6.0.tar.gz \
 && tar -xzf papi-5.6.0.tar.gz
WORKDIR /Downloads/papi-5.6.0/src
RUN ./configure --prefix=/opt/papi \
 && make -j$JOBS \
 && make install

# TAU 

WORKDIR /Downloads

# Git version mpi linking it not currently working
# RUN git clone https://github.com/UO-OACISS/tau2.git
# WORKDIR /Downloads/tau2
# RUN ./configure -cc=mpicc -c++=mpic++ -fortran=gfortran -mpi \
#     -pthread -bfd=download -unwind=download -pdt=/opt/pdt \
#     -pdt_c++=g++ -prefix=/opt/tau2 -adios=/opt/adios2 \
#     -papi=/opt/papi \
#  && make -j$JOBS install


RUN	wget http://tau.uoregon.edu/tau.tgz && \
	tar -xvzf tau.tgz

WORKDIR /Downloads/tau-2.29


RUN ./configure -cc=mpicc -c++=mpic++ -fortran=gfortran -mpi -pthread -bfd=download -unwind=download -pdt=/opt/pdt -pdt_c++=g++ -prefix=/opt/tau2 -adios=/opt/adios2 -papi=/opt/papi -cuda=/usr/local/cuda && \
	make -j$JOBS install

FROM chimbuko/adios2.cuda10.1:latest

COPY --from=tau-build /opt /opt

ENV PATH=/opt/tau2/x86_64/bin/:${PATH}
ENV TAU_MAKEFILE=/opt/tau2/x86_64/lib/Makefile.tau-papi-mpi-pthread-cupti-pdt-adios2
ENV TAU_OPTIONS="-optShared -optRevert -optVerbose -optCompInst"
