packages:
  python:
    buildable: false
    externals:
    - spec: python@3.6.0
      prefix: /usr
  libfabric:
    buildable: false
    externals:
    - spec: libfabric@1.9.0
      prefix: /opt/libfabric
  zlib:
    buildable: false
    externals:
    - spec: zlib@1.2.11
      prefix: /usr
  ncurses:
    buildable: false
    externals:
    - spec: ncurses@6.1
      prefix: /usr
  m4:
    buildable: false
    externals:
    - spec: m4@1.4.18
      prefix: /usr
  pkg-config:
    buildable: false
    externals:
    - spec: pkg-config@0.29.1
      prefix: /usr
  bzip2:
    buildable: false
    externals:
    - spec: bzip2@1.0.6
      prefix: /usr
  perl:
    buildable: false
    externals:
    - spec: perl@5.26.1
      prefix: /usr
  libtool:
    buildable: false
    externals:
    - spec: libtool@2.4.6
      prefix: /usr
  diffutils:
    buildable: false
    externals:
    - spec: diffutils@3.6
      prefix: /usr
  openssl:
    buildable: false
    externals:
    - spec: openssl@1.1.1
      prefix: /usr
  cmake:
    buildable: false
    externals:
    - spec: cmake@3.17.0
      prefix: /opt/cmake-3.17.0-Linux-x86_64/
  autoconf:
    buildable: false
    externals:
    - spec: autoconf@2.69
      prefix: /usr
  automake:
    buildable: false
    externals:
    - spec: automake@1.15
      prefix: /usr
  cereal:
    buildable: false
    externals:
    - spec: cereal@1.3.0
      prefix: /opt/cereal
  openblas:
    buildable: false
    externals:
    - spec: openblas@0.2.20
      prefix: /usr
  openmpi:
    buildable: false
    externals:
    - spec: openmpi@4.0.4
      prefix: /opt/openmpi4.0.4
