packages:
  binutils:
    externals:
    - spec: binutils@2.30
      prefix: /usr
    buildable: False
  coreutils:
    externals:
    - spec: coreutils@8.28
      prefix: /usr
    buildable: False
  diffutils:
    externals:
    - spec: diffutils@3.6
      prefix: /usr
    buildable: False
  findutils:
    externals:
    - spec: findutils@4.7.0-git
      prefix: /usr
    buildable: False
  openssh:
    externals:
    - spec: openssh@7.6p1
      prefix: /usr
    buildable: False
  openssl:
    externals:
    - spec: openssl@1.1.1
      prefix: /usr
    buildable: False
  git:
    externals:
    - spec: git@2.17.1~tcltk
      prefix: /usr
    buildable: False
  gmake:
    externals:
    - spec: gmake@4.1
      prefix: /usr
    buildable: False
  libtool:
    externals:
    - spec: libtool@2.4.6
      prefix: /usr
    buildable: False
